/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

/*
 * File: /System/Library/Frameworks/Message.framework/Versions/B/Message
 * UUID: 7314B194-6FC8-7CEE-81AE-2AF4ADE34AAA
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1082.0.0, Compatibility version: 1.0.0
 *
 *       Objective-C Garbage Collection: Supported
 */

@interface MessageRouter : NSObject

+ (void)initialize;
+ (id)writeRulesTimer;
+ (void)setWriteRulesTimer:(id)arg1;
+ (void)scheduleWriteRules;
+ (void)unScheduleWriteRules;
+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
+ (void)_updateICalRule:(BOOL)arg1;
+ (void)_setupAddInvitationDefault;
+ (void)_iCalSettingChangedFromICal:(id)arg1;
+ (BOOL)_hasColorRules;
+ (long long)colorChangeCounter;
+ (void)setColorChangeCounter:(long long)arg1;
+ (void)enqueueColorRulesDidChange;
+ (BOOL)_colorRuleExistsAfterRule:(id)arg1;
+ (BOOL)colorsUpdateDynamically;
+ (void)ruleAffectingColorsDidChange:(id)arg1;
+ (void)ruleDidChange:(id)arg1;
+ (void)mailboxWillBeRenamedOrInvalidated;
+ (void)_mailboxBecameInvalid:(id)arg1;
+ (void)_accountWillBeDeleted:(id)arg1;
+ (void)_mailboxWasRenamed:(id)arg1;
+ (id)defaultAppleEmailAddresses;
+ (id)_defaultSortRules;
+ (id)sortRulesPath;
+ (id)oldSortRulesPath;
+ (id)iCalRule;
+ (BOOL)_setICalRule:(id)arg1;
+ (id)_sortRulesFromDictionaryRepresentations:(id)arg1 junkRule:(id *)arg2 iCalRule:(id *)arg3;
+ (id)_sortRuleDictionaryRepresentations;
+ (void)_setupSortRules;
+ (id)_readRulesFromDiskOldStyle;
+ (id)_readRulesFromDisk;
+ (void)writeRulesToDiskInBackground;
+ (void)synchronouslyWriteRulesToDisk;
+ (id)rules;
+ (unsigned long long)numberOfRules;
+ (id)ruleAtIndex:(unsigned long long)arg1;
+ (void)removeRuleAtIndex:(unsigned long long)arg1;
+ (void)insertRule:(id)arg1 atIndex:(unsigned long long)arg2;
+ (void)addRule:(id)arg1;
+ (void)removeRule:(id)arg1;
+ (void)tryToReconnectAutoDeactivatedRules;
+ (void)loadDestinationMailboxes;
+ (void)_mailboxListingChanged:(id)arg1;
+ (id)headersRequiredForRouting;
+ (void)headersRequiredForRoutingDidChange;
+ (void)putRulesThatWantsToHandleMessage:(id)arg1 intoArray:(id)arg2 colorRulesOnly:(BOOL)arg3;
+ (id)colorForMessage:(id)arg1 highlightTextUsingColor:(char *)arg2;
+ (int)junkMailBehavior;
+ (void)setJunkMailBehavior:(int)arg1;
+ (void)evaluateJunkMailBehaviorFromRules;
+ (void)_ensureJunkRuleBehaviorMatchesPreference;
+ (void)reevaluateJunkMessagesInMailboxes:(id)arg1;
+ (id)junkMailRuleForBehavior:(int)arg1 abCriterion:(BOOL)arg2 ahCriterion:(BOOL)arg3 fnCriterion:(BOOL)arg4;
+ (id)junkMailRule;
+ (void)setJunkMailRule:(id)arg1;
+ (id)userJunkMailRule;
+ (id)defaultJunkMailRule;
+ (BOOL)junkMailEvaluationAfterRules;
+ (void)setJunkMailEvaluationAfterRules:(BOOL)arg1;
+ (BOOL)junkMailTrustHeaders;
+ (void)setJunkMailTrustHeaders:(BOOL)arg1;
+ (id)junkMailHeaderFlags;
+ (void)_applyRulesToMailboxUids:(id)arg1;
+ (void)applyRulesAsynchronouslyToMailboxUids:(id)arg1;
+ (BOOL)addInvitationsToICalAutomatically;
+ (BOOL)_addICalRule;
+ (void)setAddInvitationsToICalAutomatically:(BOOL)arg1;
+ (void)addInvitationsToICalFromMessages:(id)arg1;
+ (void)installNewRulesFromPlist:(id)arg1;
- (BOOL)_routeMessagesIndividually;
- (id)routeMessages:(id)arg1 fromStores:(id)arg2;
- (void)asynchronouslyRouteMessages:(id)arg1;
- (void)routeQueuedMessages;
- (void)waitForRoutingToFinish;
- (void)setStore:(id)arg1;
- (void)setEstimatedNumberOfMessagesToRoute:(unsigned long long)arg1;
- (void)dealloc;
- (void)finalize;
- (void)setIsUserAction:(BOOL)arg1;
- (BOOL)dataWillBeSyncedVersion:(id *)arg1 data:(id *)arg2 type:(id)arg3;
- (BOOL)dataWasSyncedVersion:(id)arg1 newData:(id)arg2 acceptedChanges:(id)arg3;
- (id)newRulesArrayWithJunkAndICalRules:(id)arg1;

@end

